labels:
  - name: docs
    paths:
      - '*.md'
  - name: flake-update
    paths:
      - 'flake.nix'
  - name: nixpkgs-update
    paths:
      - 'flake.lock'
  - name: in-review
    paths:
      - './**'
