docs:
- head-branch: [ '^docs', 'docs' ]
- changed-files:
  - any-glob-to-any-file: '*.md'

flake-update:
- head-branch: [ '^flake', 'flake' ]
- changed-files:
  - any-glob-to-any-file: 'flake.nix'

nixpkgs-update:
- head-branch: [ '^update', 'update' ]
- changed-files:
  - any-glob-to-any-file: 'flake.lock'

in-review:
- head-branch: [ '.*' ]
- changed-files:
  - any-glob-to-any-file: './**'

bugfix:
- head-branch: [ '^bugfix', 'bugfix' ]

feature:
- head-branch: [ '^feature', 'feature' ]
