# One CLI to format the code tree - https://git.numtide.com/numtide/treefmt

[formatter.nix]
command  = "nixfmt"
options  = [ "-w 120", "-v" ]
includes = [ "*.nix" ]
excludes = []

[formatter.yaml]
command  = "yamlfmt"
options  = [ "" ]
includes = [ "*.yaml", "*.yml" ]
excludes = []

[formatter.json]
command  = "jsonfmt"
options  = [ "-w", '-i "  "' ]
includes = [ "*.json" ]
excludes = []

[formatter.md]
command  = "markdownlint"
options  = [ "--fix", "--disable 'MD013 MD033'"]
includes = [ "*.md" ]
excludes = []

