name: Format Code

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - name : Checkout repository
      uses : actions/checkout@v4

    - name : Install Nix
      uses : DeterminateSystems/nix-installer-action@main

    - name : Install nixfmt
      run  : nix-env -f "<nixpkgs>" -iA nixpkgs.nixfmt-rfc-style

    - name : Install treefmt
      run  : nix-env -f "<nixpkgs>" -iA nixpkgs.treefmt

    - name : Run nixfmt
      run  : nixfmt .

    - name : Run treefmt
      uses : isbecker/treefmt-action@v1
      with :
        github_token: ${{ secrets.GITHUB_TOKEN }}
        version: 'latest'
        fail_on_change: 'true'
